routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

//Route::get('/', function () {
//    return view('welcome');
//});

Auth::routes();

Route::get('/', 'HomeController@index')->name('welcome');
Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');

//////////////////////////////////////////////////////
// All admin groups should use the isAdmin middleware
// ensuring that the user has admin privilege
//////////////////////////////////////////////////////
Route::middleware('isAdmin')->name('admin.')->group(function () {

// Add dates
   Route::name('addDates')->post('/admin.addDates', 'SchemaController@addDates');

// Add existing users to a training
   Route::name('addMember')->post('/admin/addMember', 'SchemaController@addMember');

// Add new user to the Users table
   Route::name('addNewUser')->post('/admin.addNewUser', 'SchemaController@addNewUser');

// Remove dates
   Route::name('removeDates')->post('/admin.removeDates', 'SchemaController@removeDates');

// Remove member from a training
   Route::name('removeMember')->post('/admin/removeMember', 'SchemaController@removeMember');

// Show add/remove dates view
   Route::name('showAddRemoveDates')->get('/admin/AddRemoveDates/{training}', 'SchemaController@showViewAddRemoveDates');

// Show add/remove group view
   Route::name('showAddRemoveGroup')->get('/admin/AddRemoveGroup', 'SchemaController@showViewAddRemoveGroup');
   
// Show view AdminComments
   Route::name('showComments')->get('/admin/comments/{training}', 'SchemaController@showViewAdminComments');

// Show add/remove members view
   Route::name('showMembers')->get('/admin/members/{training}', 'SchemaController@showViewMembers');

// Show admin menu
   Route::name('showMenu')->get('/admin/menu/{training}', 'SchemaController@showAdminMenu');

// Show register new user form
   Route::name('showRegisterUser')->get('/admin/showRegisterUser/{training}', 'SchemaController@showRegisterUser');

// Update comments
   Route::name('updateComments')->post('/schema.updateComments', 'SchemaController@updateComments');

});



/////////////////////////////////////////////////////////////////
// All routes in the schema groups should use the auth middleware
// ensuring that the user is logged in
/////////////////////////////////////////////////////////////////
Route::middleware('auth')->name('schema.')->group(function () {

   // Show the schema
   Route::name('index')->get('/schema.index/{trainingId?}', 'SchemaController@index');

   //Show edit view for one user for  attendance update
   Route::name('showEdit')->get('/schema/edit/{training}', 'SchemaController@showViewEdit');
   
   // Update attendance (for one user)
   Route::name('updateAttendance')->post('/schema.updateAttendance', 'SchemaController@updateAttendance');

});

resources/views/AddRemoveDates.blade.php
@extends('layouts.app')
@section('content')
<h1>Lägg till/ta bort datum</h1>
 <div class="container">

     <br>
      <form action="{{ route('admin.addDates')}}" method="POST">
          {{ csrf_field() }}
          <input type="hidden" name="trainingId" value="{{$training->id}}">
          <fieldset>
            <legend>Ange datum som skall läggas till</legend>
      Befintliga datum är {{$weekdays}} kl. {{$danceTime}}
      Senaste datum är {{$lastTrainingDate->training_date}}
      <br><br>
         <div class="table-responsive" style="overflow-x:auto; overflow-y:hidden;">
             Lägg till <input type="number" id="quantity" name="quantity" min="1" max="15" size="4" value="1"> 
            <select id="weekdays">
              <option value="0">Söndagar</option>
              <option value="1">Måndagar</option>
              <option value="2">Tisdagar</option>
              <option value="3">Onsdagar</option>
              <option value="4">Tordagar</option>
              <option value="5">Fredagar</option>
              <option value="6">Lördagar</option>
            </select>
             från och med
             <input type="date" id="startDate" name="startDate", oninput="dateIsChanged()" value="{{$nextDate}}">
        </div>
          <br>
          <p style="float:right;">
         <button type="submit" class="btn btn-primary" style="margin-right:10px;">Lägg till datum</button>
            <a href="{{route('admin.showMenu',['training' =>$training])}}" class="btn btn-primary" role="button">
              Avbryt
            </a>
          </p>
          </fieldset>

      </form>
     <br>
     <form action="{{ route('admin.removeDates')}}" id="removeForm" method="POST">
          {{ csrf_field() }}
          <input type="hidden" name="trainingId" value="{{$training->id}}">
          <fieldset>
            <legend>Markera datum som skall tas bort</legend>
            <table class="table table-bordered table-sm table-sd-schema" style="max-width:250px;">
               <thead>
                  <th class="text-nowrap text-center">Datum</th>
                  <th class="text-nowrap text-center">Kommentar</th>
                  <th class="text-nowrap text-center" style="padding:2px 5px 2px 5px;">Ta bort</th>
               </thead>
               <tbody>
         @foreach ($trainingDates as $trainingDate)
            @php
               $deleteName='delete_'.$trainingDate->id;
            @endphp
                  <tr class='status'>
                     <td class="text-nowrap" style="padding:1px 7px;">{{$trainingDate->training_date}}</td>
                     <td class="text-nowrap" style="padding:1px 7px;" >
                         {{$trainingDate->comment}}
                     </td>
                     <td style="padding:2px 5px 2px 5px;"><input type="checkbox"  class="inp" onclick="hideOrShowRemoveButton()" name="{{$deleteName}}"> Bort</td>
                  </tr>
         @endforeach
               </tbody>
            </table>
            <br>
            <p style="float:right;">
            <button type="submit" class="btn btn-primary" id="removeButton" onclick="return checkDeletes()" style="margin-right:10px;">Ta bort datum</button>
            <a href="{{route('admin.showMenu',['training' =>$training])}}" class="btn btn-primary" role="button">
              Avbryt
            </a>
          </p>

         </fieldset>

     </form>
 </div>
@section('scripts')
<script>
 
window.onload = function() {
  checkWeekday();
  hideOrShowRemoveButton();
};
function checkWeekday() {
   let element = document.getElementById("weekdays");
    element.value = "{{$weekDaysNumber}}";
}

//  If the user picks a day from the date picker, update the the value in the
//  weekdays SELECT input element to show correct the day of week
function dateIsChanged() {
   var selectedDate = document.getElementById("startDate").value;
   var dayOfWeek= new Date(selectedDate).getDay();
   console.log(selectedDate+' veckodag='+dayOfWeek);
   let element = document.getElementById("weekdays");
   element.value= dayOfWeek;
}
//Hide Remove button if  no date is marked for removal
function hideOrShowRemoveButton() {
      var n= countDeletes();
      console.log(n + ' deletes');
      const removeButton = document.getElementById("removeButton");
      if (n==0) {
          removeButton.style.display = "none";      
      } else {
          removeButton.style.display = "inline-block";      
      }
   }
   
   function countDeletes() {
      var checkBoxes=  document.querySelectorAll('.inp');
      console.log(checkBoxes.length + ' checkBoxes');
      let n=0;
      for (let i = 0; i < checkBoxes.length; i++) {
         if (checkBoxes[i].checked) {
            n++;
         }
      }
      return n;
   }
   
   function checkDeletes() {
      var n= countDeletes();
      if (n> 0 ) {
         return confirm('Är du säker? Du har markerat '+n+' datum för borttag.');
      } else {
         return true;
      }
   }     

</script>
@endsection

@endsection

resources/views/AddRemoveGroup.blade.php
@extends('layouts.app')
@section('content')
<h1>Admin Menu</h1>

  <div class="container">
      <div class="table-responsive" style="overflow-x:auto; overflow-y:hidden;">
          <br><br>
          <h2>Funktionen Lägga till/Ta bort grupp implementeras vid behov</h2>
     </div>
 </div>
<!--</div>-->
@section('scripts')

@endsection

@endsection

resources/views/AdminComments.blade.php
@extends('layouts.app')
@section('content')

@php
    $userId=$currentUser->id;
    $tableMaxWidth=520;
    $group= $currentUser->group;
    if ($group > 1) {
        $tableMaxWidth=700;
    }
@endphp
  <div class="container">
      <div class="table-responsive" style="overflow-x:auto; overflow-y:hidden;">

        <form id="myForm" action="{{ route('admin.updateComments')}}" method="POST">
          {{ csrf_field() }}
          <input type="hidden" name="trainingId" value="{{$training->id}}">
          <fieldset>
            <legend>Ändra kommentarer</legend>
            
        <table class="table table-bordered" style="max-width:{{$tableMaxWidth}}px;">
        
            <thead>
              <th style="vertical-align:middle;" class="text-nowrap text-center">Datum</th>
              <th class="text-nowrap text-center" style="width:290px;">Kommentar</th>
            </thead>
            <tbody>

        @foreach ($trainingDates as $trainingDate)
               <tr class='status'>
                  <td class="text-nowrap" style="max-width:90px !important;height:32px; padding:2px 7px;vertical-align:middle;">{{$trainingDate->training_date}}
                  </td>
            @php
                  $commentName='comment_'.$trainingDate->id;
                  $deleteName='delete_'.$trainingDate->id;
            @endphp
                  <td class="text-nowrap" style="padding:1px 7px;" >
                     <input type="text" maxlength=50 size=40 name="{{$commentName}}" value="{{$trainingDate->comment}}">
                  </td>
               </tr>
        @endforeach
            </tbody>
         </table>
            <p style="float:right;">
            <button  type="submit" class="btn btn-primary"  onclick="return checkDeletes()">Spara ändringar</button>
            <a href="{{route('admin.showMenu',['training' =>$training])}}" class="btn btn-primary" role="button">Avbryt</a>
            </p>
             </fieldset>

        </form>
     </div>
 </div>
<!--</div>-->
@section('scripts')
@endsection

@endsection

resources/views/AdminMenu.blade.php
@extends('layouts.app')
@section('content')
<h1>Admin Menu</h1>

  <div class="container">
      <div class="table-responsive" style="overflow-x:auto; overflow-y:hidden;">
         <a href="{{route('admin.showComments',['training' =>$training])}}"       class="btn btn-primary" role="button">
             Ändra kommentarer
         </a>
         <a href="{{route('admin.showAddRemoveDates',['training' =>$training])}}" class="btn btn-primary" role="button">
              Lägg till/Ta bort datum
         </a>
         <a href="{{route('admin.showMembers',['training' =>$training])}}" class="btn btn-primary" role="button">
             Medlemmar
         </a>
         <a href="{{route('admin.showAddRemoveGroup')}}" class="btn btn-primary" role="button">
             Skapa/ta bort grupp
         </a>

     </div>
 </div>
<!--</div>-->
@section('scripts')

@endsection

@endsection

resources/views/C3bGroupOld.blade.php
@extends('layouts.app')
@section('content')
<h1>C3a Måndagar</h1>
  <div class="container">
      <div class="table-responsive" style="overflow-x:auto; overflow-y:hidden;">
        @if ($edit)
        <form action="{{ route('schema.update')}}" method="POST">
          {{ csrf_field() }}
          <table class="table table-bordered table-sm table-sd-schema" style="max-width:250px;">
        @else
          <a href="{{route('schema.edit')}}" class="btn btn-primary" role="button">Ändra min närvaro</a>
          
<div class="outer">
  <div class="inner">
         
          <table class="table table-bordered" style="max-width:800px;font-size:smaller">
        @endif
            <thead>
              <th class="fix text-nowrap text-center">Datum</th>
              <th class="text-nowrap text-center">Kommentar</th>
              @if ($currentUser->authority > 1 && $edit)
              <th class="text-nowrap text-center" style="padding:2px 5px 2px 5px;">Ta bort</th>
              @else
              <th class='vertical'>Ja</th>
              <th class='vertical'>Nej</th>
              <th class='vertical'>Kanske</th>
              @endif
              @foreach ($memberNames as $memberName)
                @if (($currentUser->name==$memberName || !$edit))
                <th class="text-nowrap text-center">{{$memberName}}</th>
                @endif
              @endforeach
             </thead>
             <tbody>
             @php
               $i=0;
             @endphp
             @foreach ($trainingDates as $trainingDate)
               <tr class='status'>
               <th class="fix text-nowrap" style="padding:1px 7px;">{{$trainingDate->training_date}}</td>
               @php
                  $commentName='comment_'.$trainingDate->id;
               @endphp
               @if ($currentUser->authority > 1 && $edit) 
               <td class="text-nowrap" style="padding:1px 7px;" >
                   <input type="text" maxlength=50 size=20 name="{{$commentName}}" value="{{$trainingDate->comment}}">
               </td>
               <td style="padding:2px 5px 2px 5px;"><input type="checkbox"> Bort</td>
               @else
               <td style="padding:1px 7px;min-width:15ch;max-width:20ch;" >{{$trainingDate->comment}}</td>
               @endif
               @if (!$edit)
               <td class="text-center">{{$statusSums[$i]['Y']}}</td>
               <td class="text-center">{{$statusSums[$i]['N']}}</td>
               <td class="text-center">{{$statusSums[$i++]['M']}}</td>
               @endif
              
               @foreach ( $names as $userId => $name )
                @php
                    $status= $statuses[$userId];
                    $group= $groups[$userId];
                    $statusName='-';
                    switch ($status) {
                      case 1: if ($group==1) {
                                 $statusName='Ja';
                              } else {
                                 $statusName='1';
                              }
                              break;
                      case 2: $statusName='2';
                              break;
                      case 3: $statusName='Nej';
                              break;
                      case 4: $statusName='Kanske';
                              break;
                     }
                     $radioGroupName='status_'.$userId.'_'.$trainingDate->id;
                   @endphp
                   @if (($currentUser->name==$name && $edit))
                     <td>
                     @if ($group===1)
                        <table class="table-sd-schema" style='border:none;'>
                          <tr style='border:none;'>
                            <td style='border:none;'><input type="radio" name="{{$radioGroupName}}" value="1" class="status" {{($status==1)?'checked':''}}>
                              <span id="statusSpan">Ja</span></td>
                            <td style='border:none;'><input type="radio" name="{{$radioGroupName}}" value="3" class="status" {{($status==3)?'checked':''}}>
                              <span id="statusSpan">Nej</span></td>
                          </tr><tr style='border:none;'>
                            <td colspan="2" style='border:none;min-width:120px;text-align:center;'><input type="radio" name="{{$radioGroupName}}" value="4" class="status" {{($status==4)?'checked':''}}>
                              <span id="statusSpan">Kanske</span></td>
                          </tr>
                        </table>
                     @else
                       <table class="table-sd-schema" style='border:none;'>
                         <tr style='border:none;'>
                           <td style='border:none;min-width:75px;'><input type="radio" name="{{$radioGroupName}}" value="1" class="status" {{($status==1)?'checked':''}}>
                              <span id="statusSpan">1</span></td>
                           <td style='border:none;min-width:100px;'><input type="radio" name="{{$radioGroupName}}" value="2" class="status"  {{($status==2)?'checked':''}}>
                              <span id="statusSpan">2</span></td>
                         </tr><tr style='border:none;'>
                           <td style='border:none;'><input type="radio" name="{{$radioGroupName}}" value="3" class="status" {{($status==3)?'checked':''}}>
                             <span id="statusSpan">Nej</span></td>
                           <td style='border:none;'><input type="radio" name="{{$radioGroupName}}" value="4" class="status" {{($status==4)?'checked':''}}>
                              <span id="statusSpan">Kanske</span></td>
                         </tr>
                       </table>
                     @endif
                     </td>
                     @elseif (!$edit)
                     <td class="text-center">{{$statusName}}</td>
                     @endif
               @endforeach
               </tr>
             @endforeach
              </tbody>
            </table>

            @if ($edit)
              <button type="submit" class="btn btn-primary">Spara</button>
              <button type="cancel" class="btn btn-primary">Avbryt</button>
        </form>
        @endif
    </div>
 </div>
<!--</div>-->
@endsection

resources/views/Members.blade.php
@extends('layouts.app')
@section('content')
<h1>Medlemmar</h1>
 <div class="container">
      <label for="emailAdresses">Emailadresser: (markera alla och kopiera)</label><br>
      <textarea style="background-color:#ccc" id="emailAdresses"  cols="80">{{$emails}}</textarea>
     <br>
      <form action="{{ route('admin.addMember')}}" method="POST">
          {{ csrf_field() }}
         <input type="hidden" name="trainingId" value="{{$training->id}}">t
         <fieldset>
             <legend>Ange medlem som skall läggas till schemat <span style="white-space: nowrap;">{{$training->name}}</span></legend>
            <br>
            <div class="table-responsive" style="overflow-x:auto; overflow-y:hidden;">
      @if (count($nonMembers) > 0)
         <table class="table table-bordered table-sm" style="max-width:500px;"> 
            <thead style="font-size:1.3em;font-weight:bold; text-decoration-line: underline;">
               <th>Namn</th>
               <th>epost</th>
               <th>Antal</th>
               <th class="text-nowrap text-center">Behörighet</th>
               <th  class="text-center" style="max-width:80px;">Lägg till</th>
            </thead>
            <tbody>
         @foreach  ($nonMembers as $member)
         @php
            $addName='add_'.$member->id;
         @endphp

               <tr>
                  <td class="text-nowrap">{{$member->name}}</td>
                  <td class="text-nowrap">{{$member->email}}</td>
                  <td class="text-center">{{$member->group}}</td>
                  <td class="text-center">{{$member->authority}}</td>
                  <td style="padding:2px 5px 2px 5px;" class="text-center">
                      <input type="checkbox"  class="cbAdd" onclick="hideOrShowAddButton()" name="{{$addName}}"></td>
               </tr>
         @endforeach
            </tbody>
         </table>
      @else
         Alla registrerade användare är redan anslutna till <span style="white-space: nowrap;">{{$training->name}}</span>.
      @endif
            </div>
            <br>
            <p style="float:right;">
               <button type="submit" class="btn btn-primary" id="addButton" style="margin-right:10px;">Lägg till markerade</button>
               <a href="{{route('admin.showRegisterUser',['training' => $training])}}" class="btn btn-primary" role="button">
               Registrera ny användare
               </a>
               <a href="{{route('admin.showMenu',['training' =>$training])}}" class="btn btn-primary" role="button">
               Avbryt
               </a>
            </p>
         </fieldset>
      </form>
      <br>
      <form action="{{ route('admin.removeMember')}}" method="POST">
          {{ csrf_field() }}
          <input type="hidden" name="trainingId" value="{{$training->id}}">
          <fieldset>
            <legend>Markera medlem som skall tas bort från schemat <span style="white-space: nowrap;">{{$training->name}}</span></legend>
           <table class="table table-bordered table-sm" style="max-width:250px;">
               <thead style="font-size:1.3em;font-weight:bold; text-decoration-line: underline;">
               <th class="text-nowrap">Namn</th>
               <th class="text-nowrap text-center" style="padding:2px 5px 2px 5px;">Ta bort</th>
               </thead>
               <tbody>
         @foreach ($members as $member)
            @php
               $deleteName='delete_'.$member->user_id;
            @endphp
                  <tr class='status'>
                     <td class="text-nowrap" >{{$member->user_name}}</td>
                     <td class="text-nowrap text-center" style="padding:2px 5px 2px 5px;">
                         <input type="checkbox"  class="cbRemove" onclick="hideOrShowRemoveButton()" name="{{$deleteName}}">
                     </td>
                  </tr>
         @endforeach
               </tbody>
            </table>
            <br>
            <p style="float:right;">
            <button type="submit" class="btn btn-primary" style="margin-right:10px;" id="removeButton" onclick="return checkDeletes()">Ta bort medlem</button>
            <a href="{{route('admin.showMenu',['training' =>$training])}}" class="btn btn-primary" role="button">
              Avbryt
            </a>
          </p>

         </fieldset>

     </form>
 </div>
@section('scripts')
<script>
 
window.onload = function() {
   hideOrShowRemoveButton();
   hideOrShowAddButton();
};
//Hide Remove button if no member is marked for removal
function hideOrShowRemoveButton() {
      var n= countDeletes();
      console.log(n + ' deletes');
      const removeButton = document.getElementById("removeButton");
      if (n==0) {
          removeButton.style.display = "none";      
      } else {
          removeButton.style.display = "inline-block";      
      }
   };
   
   function countDeletes() {
      var checkBoxes=  document.querySelectorAll('.cbRemove');
      let n=0;
      for (let i = 0; i < checkBoxes.length; i++) {
         if (checkBoxes[i].checked) {
            n++;
         }
      }
      return n;
   };
   
   function checkDeletes() {
      var n= countDeletes();
      if (n> 0 ) {
         return confirm('Är du säker? Du har markerat '+n+' medlemmar för borttag.');
      } else {
         return true;
      }
   };
//Hide Add button if no user is marked for adding
function hideOrShowAddButton() {
      var n= countAdds();
       console.log(n + ' adds');
      const addButton = document.getElementById("addButton");
      if (n==0) {
          addButton.style.display = "none";      
      } else {
          addButton.style.display = "inline-block";      
      }
   };
  function countAdds() {
      var checkBoxes=  document.querySelectorAll('.cbAdd');
      let n=0;
      for (let i = 0; i < checkBoxes.length; i++) {
         if (checkBoxes[i].checked) {
            n++;
         }
      }
      return n;
   };
function copyEmails() {
  /* Get the text field */
  var copyText = document.getElementById("emailAdresses");

  /* Select the text field */
  copyText.select();
  copyText.setSelectionRange(0, 99999); /* For mobile devices */

   /* Copy the text inside the text field */
  navigator.clipboard.writeText(copyText.value);

  /* Alert the copied text */
  alert("Copied the text: " + copyText.value);
} 
</script>


@endsection

@endsection

resources/views/RegisterUser.blade.php
@extends('layouts.app')
@section('content')
  <div class="container">
      <div class="table-responsive" style="overflow-x:auto; overflow-y:hidden;">
          
      @if ($errors->any())
          <div class="alert alert-danger">
              <ul>
                  @foreach ($errors->all() as $error)
                      <li>{{ $error }}</li>
                  @endforeach
              </ul>
          </div>
      @endif


          
      <form action="{{ route('admin.addNewUser')}}" method="POST">
          {{ csrf_field() }}
          <input type="hidden" name="trainingId" value="{{$training->id}}">
          <fieldset>
            <legend>Registera användare</legend>
         <br>
         <div class="table-responsive" style="overflow-x:auto; overflow-y:hidden;border-style:none;">
             <table>
                 <tr>
                     <td><label class="left" for="first_name">Förnamn</label></td>
                     <td><input type="text" id="first_name" name="first_name"></td>
                 </tr>
                 <tr>
                     <td><label class="left" for="last_name">Efternamn</label></td>
                     <td><input type="text" id="last_name" name="last_name"></td>
                 </tr>
                 <tr>
                     <td><label class="left" for="name">Användarnamn</label></td>
                     <td><input type="text" id="name" name="name"></td>
                 </tr>
                 <tr>
                     <td><label class="left" for="password">Lösenord</label></td>
                     <td><input type="text" id="password" name="password"></td>
                 </tr>
                 <tr>
                     <td colspan="2">Lösenordet skall vara minst 6 tecken och innehålla minst en versal, en gemen och en siffra</td>
                 </tr>
                 <tr>
                     <td><label class="left" for="email">E-post</label></td>
                     <td><input type="text" id="email" name="email" size="40"></td>
                 </tr>
                 <tr>
                     <td>Singel/Par</td>
                     <td><input type="radio" id="1" name="group" checked value="1"><label class="left" for="1">Singel</label>
                         <input type="radio" id="2" name="group" value="2" style="margin-left:10px;" ><label class="left" for="2">Par</label>
                     </td>
                 </tr>
                 <tr>
                     <td><label class="left" for="authority">Behörighet</label></td>
                     <td><input type="number" id="authority" name="authority" size="4" min="1" max="{{ Auth::user()->authority}}" value="1"></td>
                 </tr>
             </table>
        </div>
          <br>
          <p style="float:right;">
         <button type="submit" class="btn btn-primary" style="margin-right:10px;">Lägg till användare</button>
            <a href="{{route('admin.showMenu',['training' => $training])}}" class="btn btn-primary" role="button">
              Avbryt
            </a>
          </p>
          </fieldset>

      </form>

     </div>
 </div>
<!--</div>-->
@section('scripts')

@endsection

@endsection

resources/views/Schema.blade.php
@extends('layouts.app')
@section('content')
<h1>Schema för  {{$training->name}}
    <a href="{{route('schema.showEdit',['training' =>$training])}}" class="btn btn-primary" role="button" style="margin-left:5px;en">
        Ändra min närvaro
    </a>
</h1>
  <div class="container">
      <div class="table-responsive" style="overflow-x:auto; overflow-y:hidden;">

        
          
<div class="outer">
  <div class="inner">
         
          <table class="table table-bordered">
        
            <thead style="height:100px; font-size:smaller;">
              <th style="height:100px;padding-top:70px !important;vertical-align:middle;" class="fix text-nowrap text-center">Datum</th>
              <th style="height:100px;" class="text-nowrap text-center">Kommentar</th>
             
             
              <th class='vertical'>Ja</th>
              <th class='vertical'>Nej</th>
              <th class='vertical' style="width:30px;">Kanske</th>
            
        @foreach ($names as $userId => $name)
                <th class="text-nowrap text-center" style="font-size:smaller">{{$name}}</th>
        @endforeach
             </thead>
             <tbody>
        @php
               $i=0;
        @endphp
        @foreach ($trainingDates as $trainingDate)
               <tr class='status'>
               <td class="fix text-nowrap" style="height:32px; padding:2px 7px;">{{$trainingDate->training_date}}</td>
            @php
                  $commentName='comment_'.$trainingDate->id;
            @endphp
               <td style="padding:1px 7px;min-width:15ch;max-width:20ch;" >{{$trainingDate->comment}}</td>
               <td class="text-center">{{$statusSums[$i]['Y']}}</td>
               <td class="text-center">{{$statusSums[$i]['N']}}</td>
               <td class="text-center">{{$statusSums[$i++]['M']}}</td>
            @foreach ( $names as $userId => $name )
                @php
                    $status= $statuses[$userId][$trainingDate->id];
                    $group= $groups[$userId];
                    $statusName='-';
                    switch ($status) {
                      case 1: if ($group==1) {
                                 $statusName='Ja';
                              } else {
                                 $statusName='1';
                              }
                              break;
                      case 2: $statusName='2';
                              break;
                      case 3: $statusName='Nej';
                              break;
                      case 4: $statusName='Kanske';
                              break;
                     }
                     $radioGroupName='status_'.$userId.'_'.$trainingDate->id;
                @endphp
                 <td class="text-center">{{$statusName}}</td>
            @endforeach
               </tr>
        @endforeach
              </tbody>
            </table>

     </div>
 </div>
<!--</div>-->
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/version.blade.php
1.5.0

resources/views/versionTime.blade.php
2021-12-09 07:30